# DDL Generation
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_management?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 165631
  sql:
    init:
      mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    # Hibernate
    properties:
      hibernate:
        default_schema: HUB
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true


# Logs
logging:
  level:
    web: trace
    sql: debug


server:
  error:
    include-exception: true
    include-stacktrace: ALWAYS

